#!/bin/bash 

OUTPUT_DIRECTORY=".biome/swift-standard-library"

mkdir -p $OUTPUT_DIRECTORY
rm -r $OUTPUT_DIRECTORY/*

for MODULE in Swift _Concurrency _Differentiation Dispatch Distributed RegexBuilder _RegexParser _StringProcessing
do
    MODULE_DIRECTORY="$OUTPUT_DIRECTORY/$MODULE"
    mkdir -p $MODULE_DIRECTORY
    swift-symbolgraph-extract -skip-inherited-docs \
        -output-dir $MODULE_DIRECTORY \
        -target x86_64-unknown-linux-gnu \
        -module-name $MODULE
done
