enum HighlightError:Error 
{
    case undefined(color:String)
}
enum Highlight:UInt8, Sendable
{
    //  special semantic identifiers. only generated by the symbolgraph extractor
    case generic = 0
    case argument
    case parameter
    
    /// an attribute like '@frozen'
    case attribute
    /// a type annotation, which appears after a colon. not all references to a 
    /// type have this classification, some references are considered identifiers
    /// an ordinary identifier, or a keyword identifier like 'init', 'deinit', and 'subscript'
    case keywordIdentifier
    case keywordDirective
    case keywordText 
    
    case identifier
    case directive
    case text
    case type
    case newlines
    /// a directive like '#warning', directive-keyword like '#if'.
    /// other text, including keywords like 'if', 'var', 'func', etc.
    
    case pseudo
    case number
    case string 
    case interpolation
    case comment
    case documentationComment
    
    case invalid
}
