@frozen public
enum Highlight:UInt8, Sendable
{
    //  special semantic identifiers. only generated by the symbolgraph extractor
    case generic = 0
    case argument
    case parameter
    
    /// an attribute like '@frozen'
    case attribute
    case comment
    /// '#warning', etc.
    case directive
    case documentationComment
    case identifier
    case interpolation
    case invalid
    /// 'init', 'deinit', 'subscript'
    case keywordIdentifier
    /// '#if', '#else', etc.
    case keywordDirective
    /// 'for', 'let', 'func', etc.
    case keywordText 
    case newlines
    case number
    // '$0'
    case pseudo
    case string 
    case text
    /// A type annotation, which appears after a colon. Not all references to a 
    /// type have this classification; some references are considered identifiers.
    case type
}